### ISSUE TITLE
Add workaround for successive disp-formula elements

### ISSUE THREAD

**Issue by pkra** [AmerMathSoc/AMS-Lens#36]
Successive `disp-formula`s get a lot of padding.  That's mostly poor authoring (since TeX is more forgiving) but we still have to deal with it.

Something like 

``` css
.formula + .formula {
  margin-top: -25px;
}
```

would counter-act the padding but still feels to much space for me (especially if a well-written multi-line disp-formula is nearby).

I would propose 

``` css
.formula + .formula {
  margin-top: -50px;
}
```
